version: '3.8'

services:
  webhookui:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_ENCRYPTION_KEY=your_secure_encryption_key_here  # Change this in production
    volumes:
      - ./data:/app/data  # Persist SQLite database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/webhooks"]
      interval: 30s
      timeout: 10s
      retries: 3